### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#142]
There's a bit of cleanup I would like to do after all the refactoring:

- [x] rename `style` to `css`
- [x] rename `src/Controller` to `src/Controllers`
- [x] split `dependencies.php` into multiple files in a `bootstrap` folder
- [x] merge all settings into one array, i.e., not have $settings['settings'] anymore
- [x] rename controllers to plural, e.g., Review**s**Controller

**Comment by joschli** [comment]
b1a465eed37ef2166ae9e2d40800a8224546190f
35cedb075c61c2f5d52d4ea922a045ef05818a44
5ca2dcffed763b377284e28af7b4115824c697c8
c01e39cc77ffba184605a9858a01b943b1daac49
fc4e40c4e255494198ecea70c6815de254492acc
