### ISSUE TITLE
Switch from task-wise to project-wise execution

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#146]
It would be much more practical to have the pipeline work project-wise (or even version-wise?), because that would give us intermediate results (e.g., on the review page) before the entire process finishes. Since we don't have the requirements check anymore at the start of each task, there's no reason why we shouldn't change from task-wise to project-wise.

It might then be more practical to chain the tasks as an actual pipeline:

    LoadProjectTask:Project[]
     -> LoadVersionsTask:ProjectVersionData[]
     -> CheckoutTask:ProjectVersionCheckout[]
     -> CompileTask:ProjectVersionCompile[]
     -> DetectTask:DetectorRun[]
     -> Publish:bool

We could the raise exceptions in case of errors, in which case the pipe backtracks to the previous task an continues from there. This might be much simpler than extending the blacklist to exclude projects/versions from subsequent tasks.

**Comment by salsolatragus** [comment]
I pushed the code. The parameter selection based on types is working now. I did not test the error cases yet, to ensure nice error messages if

1. a task requires a parameter that is unavailable,
2. a task returns a result with the same type as an earlier task, and
3. a task declares more than one parameter with the same type (will always have the same value).

Also, we need to handle tasks that raise exceptions when run. Here we should output a respective error message and backtrack, to continue with the next parameter combination.

**Comment by M8is** [comment]
I've implemented the error messages and tests so far.

> Also, we need to handle tasks that raise exceptions when run. Here we should output a respective error message and backtrack, to continue with the next parameter combination.
If a task fails on a certain input, could it return an empty list? This way we would end the recursive chain on that branch and automatically continue with the next set of inputs.

**Comment by salsolatragus** [comment]
We could do this, but why not let the tasks raise an error in case an error occurs and have the handling and reporting implemented once, in the runner? The tasks can still do a silent abort by returning an empty list. The upload tasks would do this, for example, because they have no output. I would like to distinguish failure from no output.

**Comment by salsolatragus** [comment]
Done.
