### ISSUE TITLE
Crash when skipping all versions or misuses

### ISSUE THREAD

**Issue by M8is** [stg-tud/MUBench#157]
When a task returns an empty list, the task runner fills it with a `continue`. We should not do that, since it leads to unexpected states when using collect tasks. For example, when `CollectVersions` filters all versions, we expect a silent stop. Currently, this will continue without a version available, which for the next task raises an uncaught `TaskParameterUnavailableWarning`.

I suggest we implement an empty results list as a silent stop and only continue, if a task returns `None`.

**Comment by salsolatragus** [comment]
Hm... isn't an error a better behaviour than a silent stop?

When this scenario occurs, I'm always trying to execute some task, e.g., `checkout`. If my filtering prevents this task from executing, it's very likely that I messed up the filtering... so an error/warning seems appropriate. Question is, should the collect tasks raise an error if they filter everything? Or are there cases where we want this to happen?
