### ISSUE TITLE
Create data migration script

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#169]
We need to migrate data from the old database schema to the new. To avoid conflicts with table names and to avoid accumulating more and more fragments from previous version of the schema, the best solution is probably to [copy data to a different db connection](https://stackoverflow.com/questions/34649181/multiple-database-connection-using-illuminate-database-eloquent-orm-in-codeignit).

**Comment by salsolatragus** [comment]
[db427951_1.sql.zip](https://github.com/stg-tud/MUBench/files/1479173/db427951_1.sql.zip)

**Comment by joschli** [comment]
[db_migration.zip](https://github.com/stg-tud/MUBench/files/1499099/db_migration.zip)
