### ISSUE TITLE
Reintroduce detector Id to use for table names and file paths

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#174]
To avoid problems with names, us an int it for the detectors in table names and the file-upload path.

**Comment by joschli** [comment]
if you want multiple detectors with the same name we also have to revert having the name as primary key, else all inserts of detectors with the same name will fail.

**Comment by salsolatragus** [comment]
We cannot habe multiple detectors with the same name anyways, since we use the detector name on pipeline-side to specify which detector to run. And the id is a folder name in one specific directory. Detector names are unique.

**Comment by joschli** [comment]
it seems that if we want id to be auto incrementing we have to set it as primary key.

**Comment by salsolatragus** [comment]
Hm... that means we either have to manage the ids ourselves or use the id as primary and the name as unique. I don't really see a difference. What is less work?

**Comment by joschli** [comment]
Using them as primary key again only implies that we have to do where() calls where we do find() calls at the moment. Managing the ids ourself could theoretically be more error prone but should only be one increments() call when inserting a new detector.

**Comment by joschli** [comment]
ah I forgot something. Managing them ourself could actually be more complicated, because we need to fetch the last inserted entry and increment its id by one and then use it in our new detector.

**Comment by joschli** [comment]
The implementation of this is easy to do, but it comes with the drawback that we cannot do any Detector::create calls anywhere easily, but we can just use the method of the RunsController to create Detectors.

**Comment by salsolatragus** [comment]
There should be just this one location where we create detectors anyways, i.e., when uploading findings, so I don't see a problem implementing this there. Also we're handling always only one detector at a time there, hence, the additional query to get the max Id is not a problem either. I prefer managing the Id ourselves then, because changing the primary seems to affect more code locations.

**Comment by joschli** [comment]
The create method we wanted to override is not part of the Model class instead it is part of the Builder class. We could override the newInstance method of the Model but we cannot call Detector::all(), because it produces a memory overflow. We could introduce own create and firstOrCreate methods into the Detector class, which would work, but there are already non-static versions of these methods. This results in errors from the ids but no errors when actually used.
What is your opinion on this? Should we keep it part of the RunsController or create our own static versions of the methods?

**Comment by salsolatragus** [comment]
Is `newInstance()` really the right location? It seems to me this method is also invoked to create an instance when querying the table, i.e., when existing detectors are fetched. Then it makes sense that the overruns, because `all()` invokes `newInstance()` invokes `all()`.

In any case, there's no need for `all()` in create, querying `DB::table($this->table)->max('id')` should be sufficient to compute the next Id, isn't it?

**Comment by salsolatragus** [comment]
It seems to me that Eloqent's event handlers might be a way to achieve what we want: https://laravel.com/docs/5.1/eloquent#events

**Comment by joschli** [comment]
I thought about the Eventlisteners, but they are called when the object is already created, which means we either have to already set an 'id' or make id a nullable column.
I did not think about querying the table directly... this way we can override newInstance and make it work.

**Comment by salsolatragus** [comment]
There's an `creating` event which is supposedly invoked before the insert, because you can prevent insertion, according to the example.

**Comment by joschli** [comment]
I tried this event and got an not null constraint error, i will test this again.

**Comment by salsolatragus** [comment]
I guess that confirms this event is triggered before insertion, because otherwise you shouldn't be able to break the query in a respective listener ;) As for the error, I guess it depends on what you did in the handler ;P

**Comment by joschli** [comment]
You have to add a EventDispatcher to the capsule for the Events to work. Also the EventListener of the Model that uses Events have to be flushed and the Model has to be rebooted after every TestCase else Event don't work anymore for the Tests after the first one.
d805c09d6a933592a14dd8b948ba5a9567544230

**Comment by salsolatragus** [comment]
Judging from you commit you did these things successfully, correct? Or is there some question/point for discussion?

**Comment by joschli** [comment]
No points to discuss, was just a status update on the whole matter, because it wasn't working at first. 
You have probably already seen that I fixed it in d805c09d6a933592a14dd8b948ba5a9567544230 .

**Comment by salsolatragus** [comment]
Yes, that's the commit I was talking about. Sounds good!
