### ISSUE TITLE
Use reviewer names in routes

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#175]

**Comment by joschli** [comment]
If we start using reviewer names in routes as well, we could remove their ids and make the name the primary key.

**Comment by salsolatragus** [comment]
I would prefer to keep the Id's, because this allows us to rename a reviewer consistently with a change at one place, e.g., when we have to anonymize reviews for a conference submission. I guess it makes sense to use the Id as the primary key then, because primary key as foreign key seems more natural. This way we only have to do the lookup by name for resolving routes.
