### ISSUE TITLE
Ensure that pattern compile leaves no pattern sources files in the project source directories

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#180]
Currently, after pattern compile, the pattern source files are left in the project source directories (in the build directory). Currently, I don't think this is a problem, but I would like the compile to clean up after itself to avoid future problems, e.g., if we reference the sources directly in the project folders.

**Comment by M8is** [comment]
I tested it and couldn't find any files left behind. In fact, pattern files aren't copied into the project source folder anymore. They are compiled directly from `/checkouts/<project>/<misuse>/patterns-src` using the dependency jar. 
Note that, if a version and misuse have the same id, both compiles will use the same subfolder. That is not an issue though, as they sort all files in separate subfolders anyway. (See any synthetic version/misuse as an example.)

**Comment by salsolatragus** [comment]
Okay, this satisfies me. Thanks for double checking.
