### ISSUE TITLE
Ensure findings table is created when detector has no potential hits

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#184]
Currently, we create the findings table(s) based on potential hits. When a detector does not have a single potential hit, the table is not created and the review site only shows an error ("table does not exists"). This should not happen. Instead, if no potential hit is sent, the controller should ensure the minimal table exists.

**Comment by joschli** [comment]
dbde5e2de27ab10f65c5384a9eb2b62081b04ecd
