### ISSUE TITLE
Create a script to migrate upload files

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#187]
We must migrate the files from

    /upload/{ex_id}/{det_name}/{p}/{v}/{m?}

to

    /upload/{ex_id}/{det_id}/{p}/{v}/{m?}

**Comment by joschli** [comment]
DB settings need to be set in the script and it needs to be executed from the main directory.

[migrate_files.php.zip](https://github.com/stg-tud/MUBench/files/1578462/migrate_files.php.zip)
