### ISSUE TITLE
Pipeline requests password despite default.config

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#204]
Currently, the master-dev version of the pipeline asks me for a password for the review site when I run `publish`, although credentials are provided in the `default.config`. The output displays the password as the username in the `password for` prompt. There's something broken with the defaults.

@M8is could you please check this? Thanks!

**Comment by M8is** [comment]
This should be fixed with pull request #206 as well. It was a problem with the number of init parameters.
