### ISSUE TITLE
PublishFindingsTask misses potential_hits parameter

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#205]
I have a crash in E2, when publishing findings:

    $ python mubench.pipeline/benchmark.py publish ex2 MuDetectOPAL_171213_woNPE --dataset Ex2-TSE17 --force-detect
    Starting benchmark...
        All requirements satisfied. You're good to go.
    Running CollectVersionsTask on project 'closure'
    Running CheckoutTask on project 'closure' version 319
    Running CompileVersionTask on git:https://github.com/google/closure-compiler.git#43c245f0
        Compiling project 'closure' version 319...
    Running LoadDetectorTask on <data.version_compile.VersionCompile object at 0x10eedd0f0>
    Running DetectAllFindingsTask on MuDetectOPAL_171213_woNPE
        Executing run on project 'closure' version 319...
        Run took 100.86 seconds.
    Running AllFindingsFilterTask on run on project 'closure' version 319
    Running PublishFindingsTask on {'pattern_examples': ['src/test/java/de/tu_darmstadt/stg/mudetect/aug/model/examples/StringBuilderExample.java#code()'], 'pattern_support': 14, 'startline': 2147483647, 'misuse': 'finding-0', 'target_environment_mapping': 'digraph "code()" {\nnslimit=10000;\n\n  1 [ label="com.google.javascript.rhino.Parser" shape="ellipse" ];\n  2 [ label="nf" shape="ellipse" color="gray" fontcolor="gray" ];\n  3 [ label="ts" shape="ellipse" color="gray" fontcolor="gray" ];\n  4 [ label="ts" shape="ellipse" color="gray" fontcolor="gray" ];\n  5 [ label="com.google.javascript.rhino.Parser.peekToken()" shape="box" ];\n  6 [ label="nf" shape="ellipse" color="gray" fontcolor="gray" ];\n  7 [ label="com.google.javascript.rhino.Parser.statement()" shape="box" color="gray" fontcolor="gray" ];\n  8 [ label="==" shape="box" color="gray" fontcolor="gray" ];\n  9 [ label="==" shape="box" color="gray" fontcolor="gray" ];\n  10 [ label="com.google.javascript.rhino.IRFactory.addChildToBack()" shape="box" color="gray" fontcolor="gray" ];\n  1 -> 2 [ label="qual" style="solid" color="gray" fontcolor="gray" ];\n  1 -> 3 [ label="qual" style="solid" color="gray" fontcolor="gray" ];\n  1 -> 4 [ label="qual" style="solid" color="gray" fontcolor="gray" ];\n  1 -> 5 [ label="recv" style="solid" ];\n  1 -> 6 [ label="qual" style="solid" color="gray" fontcolor="gray" ];\n  1 -> 7 [ label="recv" style="solid" color="gray" fontcolor="gray" ];\n  5 -> 8 [ label="para" style="solid" color="gray" fontcolor="gray" ];\n  5 -> 9 [ label="para" style="solid" color="gray" fontcolor="gray" ];\n  5 -> 10 [ label="rep" style="bold" color="gray" fontcolor="gray" ];\n  9 -> 6 [ label="sel" style="bold" color="gray" fontcolor="gray" ];\n}\n', 'confidence': 0.051470588235294115, 'pattern_violation': 'digraph "AUG" {\n\n  1 [ label="com.google.javascript.rhino.Parser.consumeToken()" shape="box" color="red" fontcolor="red" ];\n  2 [ label="com.google.javascript.rhino.Parser" shape="ellipse" ];\n  3 [ label="com.google.javascript.rhino.Parser.peekToken()" shape="box" ];\n  2 -> 1 [ label="recv" style="solid" color="red" fontcolor="red" ];\n  2 -> 3 [ label="recv" style="solid" ];\n}\n', 'confidence_string': '(pattern support = 14 / 34)*(pattern violations = 1 / 6)*(overlap = 3.00 / 4.00)', 'method': 'code()', 'file': 'src/test/java/de/tu_darmstadt/stg/mudetect/aug/model/examples/StringBuilderExample.java', 'rank': 0}
    Missing parameter potential_hits for task PublishFindingsTask

**Comment by M8is** [comment]
The problem is that `PotentialHits` is a list. I didn't notice that, since in my testing, I got an empty list of potential hits, which completely skipped the publish tasks. I actually changed this now; potential hits is not a list anymore. Also, there were actually more problems in the publish code. Will open a pull request once everything is working on my end.

**Comment by salsolatragus** [comment]
Weird, if being a list causes the problem, why does it work for E1 and E3, but not for E2?

**Comment by M8is** [comment]
The task runner was trying to iterate over the potential hits, which ran publish for each finding. Are you sure you ran the other experiments on this revision?
Also, I got `None is not iterable`, because `get_run_info` actually returned `update()`, which returns None.

**Comment by salsolatragus** [comment]
Hm... maybe I didn't. Will retry with the fixed version :) Thanks!
