### ISSUE TITLE
AttributeError running info

### ISSUE THREAD

**Issue by M8is** [stg-tud/MUBench#21]
Running `./mubench info` raises an AttributeError:

> Traceback (most recent call last):
>   File "./mubench.pipeline/benchmark.py", line 164, in <module>
>     benchmark.run()
>   File "./mubench.pipeline/benchmark.py", line 134, in run
>     self.runner.run()
>   File "/mubench/mubench.pipeline/task_runner.py", line 36, in run
>     response = task.process_project(project)
>   File "/mubench/mubench.pipeline/tasks/implementations/info.py", line 21, in process_project
>     super().process_project(project)
>   File "/mubench/mubench.pipeline/tasks/project_version_task.py", line 17, in process_project
>     response = self.process_project_version(project, version)
>   File "/mubench/mubench.pipeline/tasks/implementations/info.py", line 41, in process_project_version
>     elif version_compile.needs_compile_patterns():
> AttributeError: 'ProjectCompile' object has no attribute 'needs_compile_patterns'

**Comment by M8is** [comment]
I attempted a fix on the `info-fix` branch. However, we would have to make `Info` a `ProjectVersionMisuseTask`, to get info about the patterns.

**Comment by M8is** [comment]
Wait, I just noticed it already is. We just need to move the check. Whoops.

**Comment by salsolatragus** [comment]
Fixed :)
