### ISSUE TITLE
Slim does not see displayErrorDetails setting

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#214]
Somehow, Slim misses the `displayErrorDetails` setting. I set it to `true`, but errors are still not displayed and the logs says "set `displayErrorDetails` to `true` to see errors in the view". Is the settings entry at the right place?

**Comment by joschli** [comment]
I found the problem with this. We removed the second "settings" array in our settings.php, but slim actually expects an array with a "settings" key.

**Comment by salsolatragus** [comment]
Can we then just pass our setting to Slim like `['settings' => $settings]` to fix this?
