### ISSUE TITLE
Reviewer comment on detector overview page is not formatted

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#264]
The comment in the 'You comment' column on the detector overview page is not formatted with markdown. See: http://mubench.svamann.de/fse18-verify/private/experiments/1/detectors/Jadet/runs (down at `synthetic_directives` project).

**Comment by joschli** [comment]
This is going to be removed with the new review overview.

**Comment by salsolatragus** [comment]
Obsolete.
