### ISSUE TITLE
Hide tags on review page before agreement

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#273]
Tags should not be visible on the review page until agreement is reached. This includes that reviewers are unable to add tags before that point. Although I would like to do this during reviews, I don't want others to see my tags. I think other solutions (e.g., storing who added a tag and displaying selectively) to this problem are way more complex.

**Comment by joschli** [comment]
Maybe i am just missing something but couldnt we just add the tags to a review instead of the misuse?

**Comment by salsolatragus** [comment]
Hm... interesting idea. This would certainly enable us to show tags only to the respective reviewer before an agreement is reached. However, then we have multiple sets of tags per misuse to manage and display. While we could simply display the union of these sets after agreement, I'm unsure about management...

* every reviewer needs to be able to delete tags, regardless of who added them, since otherwise I have to contact somebody else to change a tagging.
* if multiple reviewers added the same tag, does deleting it from a misuse delete it from all reviews? Otherwise I would delete a tag and it is still there (just from another set). However, can this lead to weird situations?

On a related note: We could use a [custom pivot model](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many) to capture who added a label and just display it to whoever did. However, this may not work when multiple reviewers add the same label...
