### ISSUE TITLE
Use detectors' `startline` to find snippets

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#274]
When the detectors report a start line, we may use it to make snippet discovery more precise. If we find multiple snippets, we can simply check which of the snippets covers the `startline` to decide which of the snippets is relevant.

This is much easier than my suggestions in #271 and probably works well for E2.

**Comment by M8is** [comment]
@salsolatragus Assuming this works in most cases, would you rather only publish the snippet with the closest `startline`, or still publish all snippets ordered accordingly? Is the order of snippets preserved after publish?

**Comment by salsolatragus** [comment]
What do you mean by "closest"? If the line is within the candidate method, that our hit. If the line is not within the candidate method, it's not. If the line is not within any candidate method (or we have no line) then we report all candidates as before. Does that answer you question?

**Comment by M8is** [comment]
Yes, that's what I meant by closest. I was thinking to move that one to the top instead of dropping the other snippets. However, it sounds more consistent than I was thinking at first. I was worried that we would sometimes drop the wrong snippet.

**Comment by salsolatragus** [comment]
I think we should be fine as long as the detectors produce consistent/correct output. Otherwise we're doomed anyways ;)
