### ISSUE TITLE
MUBench published strange snippets

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#277]
Sometimes MUBench publishes a snippet from a different method whose signature seems unrelated to the reported signature, e.g., http://mubench.svamann.de/fse18-ext/experiments/2/detectors/Jadet/projects/bcel/versions/24014e5/misuses/finding-11

It is possible that I deleted a run and published a new one here. Maybe these snippets are leftovers from the first run?

**Comment by M8is** [comment]
By the way, your link requires login.
Public page: http://mubench.svamann.de/fse18-ext/experiments/2/detectors/Jadet/projects/bcel/versions/24014e5/misuses/finding-11

**Comment by M8is** [comment]
Weird. I've just debugged this, and it extracts the correct snippet. I have no idea where the uploaded snippet comes from.

**Comment by M8is** [comment]
P.S.: It finds the correct line number and declaring type as well.

**Comment by salsolatragus** [comment]
Hm... I think this started appearing when we switched the pipeline to multiple source directories. Might our trial of multiple candidate file paths have anything to do with it?

**Comment by M8is** [comment]
The snippet we publish seems correct.

![screenshot -2018-02-20-11-23-51](https://user-images.githubusercontent.com/9445386/36418911-a94c116e-1630-11e8-86cb-c165363f1433.png)

**Comment by salsolatragus** [comment]
Hm... this is really weird. I keep getting these problems... guess I have to check whether I can reproduce one of the cases and then debug it there.

**Comment by salsolatragus** [comment]
Ok, the problem is not in the extraction and upload, but on the review site. We [identify snippets by project, version, misuse_muid, and file](https://github.com/stg-tud/MUBench/blob/master-dev/mubench.reviewsite/src/Models/Misuse.php#L46). This fails in Experiment 2, where different misuses get the same id (i.e., `finding-N`). If two of them also happen to be in the same file, there's no way to tell them apart, so all are both (all) displayed...

An easy fix would be to include the detector name in the misuse id for Experiment 2. This would be correct, in the sense that it makes the misuse_muid unique for a particular misuse/finding. But it would result in very long ids that are ugly to display... another solution would be to include the detector in the snippet key, but then the question is whether we can still store detectors-specific snippets and metadata-specific snippets in one table... ideas, @joschli ?

**Comment by salsolatragus** [comment]
Let's go for the detector column (nullable for backwards compatibility (and metadata snippets)). This is the clean solution.
