### ISSUE TITLE
Handle static constructors in method extractor

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#281]
Static constructors (`<clinit>()`, `static()`) should be extractable.

**Comment by M8is** [comment]
In the code, it's `class C { static { /* do stuff */ } }` (without parenthesis). So we should probably support either `method: <clinit>`, `method: static`, or both in the dataset. @salsolatragus Which do you prefer?

**Comment by M8is** [comment]
Also, how do the detectors call them? We use the same logic to extract their findings, don't we?

**Comment by salsolatragus** [comment]
Jadet/Tikanga call the method `<clinit>()`, because their on Bytecode. I think it should be the same of DMMC. As for our source-code-based detectors: they are currently not analyzing static constructors, I think. I would go for `static()` though, because that is consistent with our expected method-call format.
