### ISSUE TITLE
Fix some problems with the method extractor

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#282]
There's some cases where the method extractor fails, here's my assumptions as to why:

* [Spaces after the method name](http://mubench.svamann.de/fse18-ext/experiments/2/detectors/Tikanga/projects/jigsaw/versions/205/misuses/finding-3/reviewers/sven) lead to a method-name mismatch.
* [Generics/type erasure](http://mubench.svamann.de/fse18-ext//experiments/2/detectors/Tikanga/projects/testng/versions/677302c/misuses/finding-4/reviewers/sven) lead to a parameter-type-name mismatch.
* [Generic arrays](http://mubench.svamann.de/fse18-ext/experiments/2/detectors/Tikanga/projects/testng/versions/677302c/misuses/finding-7/reviewers/sven) lead to a parameter type mismatch.

**Comment by M8is** [comment]
In `jigsaw.205`, a variable is named `enum`, which trips up the compiler. Seems like the project is compiled on an older version, which is why this only occurs in the extractor. I currently don't see any easy way to fix this.

**Comment by salsolatragus** [comment]
True, this project is compiles with Java 1.4 compatibility. In the method extractor we do not have this information. However, we're also only parsing the source code there, not interpreting it. The parser should accept everything. I found that [Javaparser has the concept of validators](https://github.com/matozoid/javaparser/blob/d4058004b7dece9bc906b559dab2edf0e4ead13d/javaparser-testing/src/test/java/com/github/javaparser/ast/validator/Java1_4ValidatorTest.java#L17) and that there are validators for the different language levels. Maybe we can fix the bug by removing all validators?

**Comment by salsolatragus** [comment]
Yes, please. Fingers crossed that migration goes smoothly...

**Comment by M8is** [comment]
I've pushed the changes. Tests are running. Works in the pipeline as well. We'll see if anything new is breaking, but the validators are completely disabled now, so that shouldn't be a problem anymore.

**Comment by salsolatragus** [comment]
Sounds awesome! Is the PR ready for another review then?
