### ISSUE TITLE
Use Return to submit review form

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#300]
I want to be able to use Return to submit the review form, e.g., when I selected a Yes in one of the decision dropdowns. This no longer works, because we moved the submit button from inside the form to the navigation bar.

(I want Return to trigger the currently selected save action, see #298)

**Comment by joschli** [comment]
Do you want to be able to save by hitting Return only after you changed something in the decision, or also after you changed something on the comment ?

**Comment by salsolatragus** [comment]
Im not sure I get the question. Hitting return in the comment editor should still result in a newline, not a form submission. We could think about submitting from the editor using CTRL+Return or Command+Return... but that didn't work before either...

**Comment by joschli** [comment]
The Editor we use makes sure that we cannot catch a Return that is used inside the Editor. I meant more the usecase that you havent touched any element on the page and you just hit Return to trigger the save action.

**Comment by salsolatragus** [comment]
I think generally its fine to have any Return trigger the save action, yes.
