### ISSUE TITLE
Detector releases

### ISSUE THREAD

**Issue by M8is** [stg-tud/MUBench#315]
I've noticed some issues with the detector releases.

* Trying to load Jadet or Tikanga by tag `tse17`, I get `HTTP Error 404: Not Found`. The URL is http://www.st.informatik.tu-darmstadt.de/artifacts/mubench/detectors/tse17/0.0.8/Tikanga.jar. The tag seems to work for GrouMiner.
* On MuDetect `fse18`/`latest`, I get `invalid MD5 checksum '725bb4b41bf6f4f9a0d8f64a915c0acb', expected 'c250f90fbc194609295073164c7c950a'`. Is this only on my end?

**Comment by salsolatragus** [comment]
Both problems should be fixed now.
