### ISSUE TITLE
Flaky test for import logic

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#357]
The review-site import test is flaky. It tests that the inserted/updated timestamps of the original data are the same as of the imported data, which is not the case if the import happened later than the original creation (saving the objects to the new database updates the timestamps). You can see the effect of this here: https://app.shippable.com/github/stg-tud/MUBench/runs/2206/1/console

Ideally, I would like the created timestamp to stay unchanged and the updated timestamp to reflect the import time. I think that would make sense, semantically. However, since there's currently nothing depending on these timestamps, I would be fine with either keeping both unchanged or excluding them from the tests, such that they changing doesn't make them fail.

**Comment by joschli** [comment]
I just opened a PR to fix the import test for now. I keep the created_at timestamp and leave the updated_at timestamp. After looking closer I realised we have multiple models with timestamps but only the run timestamps differ after the import. I currently don't have a explanation for the different behaviour.

**Comment by joschli** [comment]
Ok I found the problem. If you call a relation after switching the databases it still calls on the default connection. I am currently changing the test to actually call the right database to get the expectedRun.
