### ISSUE TITLE
Location markers have an offset of 2 and don't show the rank

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#39]
For example in http://mubench2.svamann.de/site/index.php/ex3/MuDetectXProject_170627_XLimitAndAllTypes/adempiere/1312/adempiere.2 all the markers are offset by two lines (e.g., 207 instead of 209). Furthermore, shouldn't the markers show the rank of the respective finding?

**Comment by joschli** [comment]
fixing the offset is not problem, but including the ranks in the markers does change the code formatting if the rank has more than 3 digits

**Comment by salsolatragus** [comment]
Changes the formatting in what sense? Do the marker get to broad and the code shifts to the right? Or does only the respective line shift? Or do things overlap?

Currently, the value of the marker is limited in E1&3, because when there are multiple potential hits we cannot easily identify the corresponding marker. Can we add the rank as a tooltip to the marker?

**Comment by joschli** [comment]
I tested this again and apparently this was already the case before adding the rank numbers. The pseudo-element shifts the code in the line to the right. Adding ranks just makes this more obvious. 
I tried adding a tooltip but i had no success yet.

**Comment by salsolatragus** [comment]
Can we add a marker for all lines that is colorless by default, but colored for the lines we want to mark? That would shift all lines equally (ignoring rank numbers for now).

Regarding the tooltip: Why can't we do something like this: https://www.w3schools.com/css/css_tooltip.asp

**Comment by joschli** [comment]
Yes we can shift all lines equally, this would solve the problem without the rank numbers.
I checked this exact tutorial for the tooltip, but i could not make it work with our pseudo elements.
I will try it again.

**Comment by salsolatragus** [comment]
Ok, so we can't make it work, because we have no actual element to anchor the tooltip to, but only pseudo elements. How about a compromise: We give a marker a width that's sufficient for, say, 3 digit ranks and set them to cut of additional digits. Then it doesn't shift and it's probably still sufficient in many cases. It's not perfect, but the thing breaks with multiple markers at the same line anyways ;)
