### ISSUE TITLE
Trial run failed on 4th step during setting up MuBench

### ISSUE THREAD

**Issue by Davy4fg** [stg-tud/MUBench#400]
Hi MuBench developers, thanks for sharing the nice project. 
I'd like to make a run on my side by following steps, I complete the first 3 steps. But failed on 4th, could you give me some hints? What is this for? As 5th step is give me a result like this,

davy@ubuntu:~/ai/mubench/install/path$ ./mubench reviewsite start
Starting MUBench review site at http://localhost:...
"docker run" requires at least 1 argument. See 'docker run --help'. Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...] [flags] Run a command in a new container

====================================================================================
Setup the MUBench Pipeline
$> ./mubench reviewsite init
Copy mubench.reviewsite/settings.default.php to mubench.reviewsite/settings.php.
List your reviewer credentials in settings.php below users.
$> ./mubench reviewsite start
Go to http://localhost:8080/setup/setup.php to initialize your database.
Publish misuse metadata to http://localhost:8080/.

Wei

**Comment by salsolatragus** [comment]
Thank you very much for reporting this problem. I reproduced it on my end and just pushed a fix. Please do a `git pull` in your install path and try if it works for you as well.

Please also note that we are in the process of creating a MUBench Shell, i.e., an interactive shell environment for running all the MUBench tasks, such as starting/stopping a reviewsite and running experiments. This will make maintenance of the entrypoint scripts easier (and testable) for us, and hopefully improve the user experience as well. This work is currently on the [mubench_shell branch](/stg-tud/MUBench/tree/mubench-shell).
