### ISSUE TITLE
MuBench review website showing duplicate and multiple code snippets for a single misuse

### ISSUE THREAD

**Issue by anam-dodhy** [stg-tud/MUBench#417]
### Steps to Reproduce:

1. Experiment 2 (Precision) was executed over dataset: [https://github.com/anam-dodhy/MUBench/tree/master/data/aliyun-oss-java-sdk](url) Experiment 2 (Precision) was successfully executed. 
Experiment 3 (Recall) was executed over dataset: [https://github.com/anam-dodhy/MUBench/tree/master/data/mpush](url)
2. Then the results of the datasets were successfully published on the review webiste along with their metadata. 

### Got:
Multiple code snippets in the Review Website are displayed against a selected misuse which are not related to the misuse itself. In some cases, the same code snippet is just repeated several times. Please find below example of such two cases for the datasets given above. Moreover, this issue is seen for almost all datasets in all three experiments. 

**Experiment:** 2 (Precision)
**Detector:** Findbugs
**Dataset**: aliyun-oss-java-sdk [https://github.com/anam-dodhy/MUBench/tree/master/data/aliyun-oss-java-sdk](url)
**Finding**: 19
![experiment 2](https://user-images.githubusercontent.com/28350571/46471216-85b71900-c7d9-11e8-8368-b546a3fd4eb5.png)

**Experiment:** 3 (Recall)
**Detector:** Findbugs
**Dataset**: mpush [https://github.com/anam-dodhy/MUBench/tree/master/data/mpush](url)
**Misuse**: 3
![experiment 3](https://user-images.githubusercontent.com/28350571/46471019-e7c34e80-c7d8-11e8-89f2-de0d2f58a0c5.png)

### Expected:
One code snippet for each misuse.

cc @akwick

**Comment by salsolatragus** [comment]
Thank you very much for reporting this issue. Luckily, it has already been fixed with 
d28583d .

If you set up your review site July 2018 or later, it should be sufficient to replace `src/Models/Misuse.php` with [the current version of that file from `master`](../blob/master/mubench.reviewsite/src/Models/Misuse.php).

Please report back if this doesn't solve the problem for you.

**Comment by akwick** [comment]
It worked, but I had to replace the following files as well: 
* `src/Controllers/RunsController.php`
* `templates/detector.phtml`
* `src/Controllers/ReviewsController.php `
* `src/Models/RunsResult.php`
* `src/Models/DetectorResult.php`
* `src/Models/ExperimentResult.php`

**Comment by salsolatragus** [comment]
Thanks for reporting back! Admittedly, by replacing the `Misuse.php` file you pulled some changes that needed corresponding changes in other file. Glad the number of files to replace was still relatively small. To fix your concrete problem, it probably would've been sufficient to just replace the one changed method in `misuse.php`, but a full upgrade, like you did, is the cleaner solution anyways ;)
