### ISSUE TITLE
Checkout of battleforge and itext fails

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#432]
As reported by @akwick, the checkout of both project fails. It seems the repositories have been (re)moved. This brings me back to the idea of morroring the repositories to the MUBench GitHub organizations to "persist" them... for the git projects this is probably straightforward. Can we simply use the git-bridge to do the same for the SVN projects?

**Comment by kanghj** [comment]
Any idea where the repository for itext is now? It looks like the svn repository has been removed entirely?

I found https://github.com/itext/itextpdf/, but I am not sure how to map the reversion "5091" to a tag/release in the git repository.

**Comment by salsolatragus** [comment]
@kanghj If the git was created through a conversion of the SVN repo, then we might be lucky to find the SVN commit Id in the git commit message. Otherwise, we might use the commit date to narrow down the number of git commits to check for the right one. However, it is entirely possible that 5091 doesn't exist anymore (e.g., because the SVN state was imported in a single commit without preserving the older history... I didn't check this yet).

**Comment by kanghj** [comment]
@salsolatragus I may have found a commit close to it: 
https://github.com/itext/itextpdf/commit/4e15425f4a8a68e5ed2344a11d029fdf6b659f0d 

The commit message indicates `git-svn-id: https://svn.code.sf.net/p/itext/code/trunk@5091 3a709846-db2a-4fbd-be0b-eb932eee6479`

Unfortunately, based on https://github.com/stg-tud/MUBench/blob/master/data/itext/versions/5091/version.yml, it seems that we need revision 5090 which I wasn't able to locate.

**Comment by salsolatragus** [comment]
@kanghj good work! We can use the [parent commit](https://github.com/itext/itextpdf/commit/adda8eb38978eeea6e86aca64ae746754c103dae), which corresponds to 5089 in version.yml, because we just need a version _before_ the fix (that came with 5091) and the diff between these two commits is really just the fix. Can you create a pull request with the GitHub repo in project.yml and the respective git commit Ids in version.yml and misuse.yml?

**Comment by salsolatragus** [comment]
@kanghj @akwick it seems we have resolved the issue for itext, but the battleforge repo seems to be gone for good... I, at least, couldn't find any trace of it... we could recreate the relevant version from the [experiment reproduction pack](http://www.st.informatik.tu-darmstadt.de/artifacts/mudetect/), which contains all checkouts. Since this was an SVN repo, we cannot reproduce the history, but HEAD and the relevant version 878 could be recovered this way. Any other ideas?

**Comment by kanghj** [comment]
@salsolatragus Yes, I haven't been able to find any trace of it too. I will try to find the relevant version from the reproduction package (maybe over a weekend this month). In fact, I have downloaded the data, but can you give some more instruction on how to unpack the zip file? 

I have tried using `cat` to combine them into  a single file but I haven't had success unzipping it:

```
$ cat mubench-md-study-data.zip > md.zip
$ cat mubench-md-study-data.z0* >> md.zip
$ unzip md.zip
Archive:  md.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of md.zip or
        md.zip.zip, and cannot find md.zip.ZIP, period.
```

**Comment by salsolatragus** [comment]
I've created a "shallow" mirror of battleforge, containing just the relevant revision, on GibHub and changed the dataset to reference it. Should work again.
