### ISSUE TITLE
Reproduction instructions for MSR 2019 paper

### ISSUE THREAD

**Issue by kanghj** [stg-tud/MUBench#433]
Hello @salsolatragus!

Thanks for the really nice work on MUBench and the various papers on API misuse! They taught me a lot. :)
 
Referring to the latest paper "Investigating Next Steps in Static API-Misuse Detection",
MuBench has been extended with the data from Legunsen's et al., but looking at https://github.com/stg-tud/MUBench/blob/master/data/datasets.yml under Legunsen-ASE16, there are only 77 line, while the paper reported 107 new misuses. 

It will be wonderful if nice reproduction instructions similar to the TSE reproduction instructions can be added. :) 

Edit:

Oops, I didn't notice "FSE18-Extension" for some reason. There are 108 lines of there, so this is probably it!

I also found the wonderful artifact website http://www.st.informatik.tu-darmstadt.de/artifacts/mudetect/! But http://www.st.informatik.tu-darmstadt.de/artifacts/mudetect/mubench-repl-data/review-site-anonymized.zip is giving a 404.

**Comment by salsolatragus** [comment]
Hi @kanghj,

sorry for the late reply.

I see you've already found the extension dataset yourself :)
I've fixed the review site and it now links to [the final version of the review site](http://www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/fse18/).

Hope this still comes in time to be of help.
