### ISSUE TITLE
Why is our Docker container so large?

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#44]
I find it surprising that our image has ~1.5G, considering that the base image has only ~140M and we don't install that much... where is the space going? What can we do about it?

**Comment by joschli** [comment]
With every RUN command we use in our dockerfile the container gets a new layer, these layers make the container incredible large. Even if you install a package in one RUN and remove it again in another RUN it makes the file larger.  If we want to make the image smaller we have to reduce the amount of RUN statements and remove packages that we only use while building the container in the same run statement.

**Comment by salsolatragus** [comment]
Interesting. Are there best practices out there how to do this? I mean, this seems like a common problem.

**Comment by joschli** [comment]
- use as few layers as possible
- group commands into one RUN statement when possible
- use -–no-install-recommends when installing packages
- remove no longer used packages or files in the same instruction if possible

**Comment by salsolatragus** [comment]
Can you post a link to you source?

We should definitively work on this, but this is low priority right now.

**Comment by joschli** [comment]
There is no official sources, these are the tips i gathered from multiple blog posts.

i did a quick test by reducing the amount of run statements, it didnt help too much. I think the biggest reduction comes from not installing the recommended packages, but this failed when i was testing it because some of them are currently needed.

**Comment by salsolatragus** [comment]
Please focus on the more urgent tasks first. I put this on "on hold" for a reason ;)

**Comment by salsolatragus** [comment]
Fix with new Docker image (80f01b4ae56a5ab9aea7e0b6aacba305a496379c).
