### ISSUE TITLE
How can i get the source code of misuse

### ISSUE THREAD

**Issue by yuningkang** [stg-tud/MUBench#442]
hello sir
i want to get the source code of the misuses ，but i have no idea how to get them，could you tell me  how，appreciate it！

**Comment by salsolatragus** [comment]
Hi,

With the command `pipeline checkout` you can download the source code. It will be downloaded into the `mubench-checkouts` folder. Please check `pipeline checkout -h` for additional details on the command line options. 

Does that answer your question?

**Comment by yuningkang** [comment]
thank you sir，it is really helpful，but i can‘ t export the source code to my computer， i wonder if it is possible running this process without docker

**Comment by salsolatragus** [comment]
You can [copy data from a Docker container to your host system](https://stackoverflow.com/questions/22049212/copying-files-from-docker-container-to-host). Of course, you may also setup the MUBench pipeline locally, to checkout into a folder on your host system. For this you'd need to install the necessary dependencies. See our Docker file for what these are: 

* https://github.com/stg-tud/MUBench/blob/master/docker/Dockerfile#L16-L41
* https://github.com/stg-tud/MUBench/blob/master/docker/Dockerfile#L81

**Comment by yuningkang** [comment]
appreciate it for your help sir！！
