### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: No index file './checkouts/_examples/index.csv'.

### ISSUE THREAD

**Issue by DehengYang** [stg-tud/MUBench#447]
Sorry for interrupting you with this issue. When I ran `pipeline run ex2 MuDetectXP --only chensun` using the docker image (i.e., 
`docker run -it -v mubench-checkouts:/mubench/checkouts -v mubench-findings:/mubench/findings --rm -p 8080:80 svamann/mubench:stable`), the following error occurs:

```
md5: 720180958805fe42a0bf387e1fd519a1
message: "Failed to execute 'java -jar \"/mubench/detectors/MuDetectXP/fse18/MuDetectXP.jar\"\
  \ detector_mode \"0\" target_src_path \"/mubench/checkouts/chensun/cf23b99/build/CS5430/src/\"\
  \ target_classpath \"/mubench/checkouts/chensun/cf23b99/build/build/classes/java/main/\"\
  \ dep_classpath \"/mubench/checkouts/chensun/cf23b99/dependencies/commons-codec-1.10.jar:/mubench/checkouts/chensun/cf23b99/original-classes.jar\"\
  \ target \"/mubench/findings/mine_and_detect/MuDetectXP/chensun/cf23b99/findings.yml\"\
  \ run_info \"/mubench/findings/mine_and_detect/MuDetectXP/chensun/cf23b99/run.yml\"\
  ': === ERROR ===\nException in thread \"main\" java.io.FileNotFoundException: No\
  \ index file './checkouts/_examples/index.csv'.\n\tat de.tu_darmstadt.stg.mubench.CrossProjectStrategy.getIndexFilePath(CrossProjectStrategy.java:154)\n\
  \tat de.tu_darmstadt.stg.mubench.CrossProjectStrategy.detectViolations(CrossProjectStrategy.java:34)\n\
  \tat de.tu_darmstadt.stg.mubench.cli.MuBenchRunner.detect(MuBenchRunner.java:82)\n\
  \tat de.tu_darmstadt.stg.mubench.cli.MuBenchRunner.detect(MuBenchRunner.java:71)\n\
  \tat de.tu_darmstadt.stg.mubench.cli.MuBenchRunner.run(MuBenchRunner.java:61)\n\t\
  at de.tu_darmstadt.stg.mubench.MuDetectCrossProjectRunner.main(MuDetectCrossProjectRunner.java:9)\n"
result: error
runtime: 0.11809277534484863
timestamp: 1599112027
```

I cannot find any index.csv file in the /mubench folder... so I fail to reproduce the experiment. Any help or guidance would sincerely appreciated. Thank you!

**Comment by salsolatragus** [comment]
Ups, sorry, this one slipped me through... I'm terribly sorry. I don't get to work on this very much these days.

I guess this comes too late for you, but for the sake of documentation, at least: To reproduce the cross-project experiment (MuDetectXP), you would need [the experiment reproduction package from our artifact page](http://www.st.informatik.tu-darmstadt.de/artifacts/mudetect/), which should contain the index.

**Comment by DehengYang** [comment]
Thank you very much for your kind help! Your kind advice still help. 

And could you spare some minutes to reply my email to you last week (tiltled "Looking for your guidance on the API misuse identification (about Mubench)")? It would be sincerely appreciated if any advice could be provided. Thank you!

**Comment by salsolatragus** [comment]
I'm sorry, I didn't get that email or it got lost in my spam filter. Could you pls resend? I'll do my best to answer promptly!

**Comment by DehengYang** [comment]
Thank you so much for your kind help and generousity! I have resent it to your email account which ends with cqse.eu" with the same title. Thank you!
