### ISSUE TITLE
File access conflicts on Windows

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#46]
Apparently, we sometimes get file-access conflicts, especially with svn checkouts on Windows, when files in the mounted `/mubench/` directory are accessed from within Docker and from the OS at the same time. I think the best solution would be to use a directory within docker for the processing and copy over the results into the mounted directory. Question is: Can we do this in a way that works both within and outside the Docker container?

**Comment by joschli** [comment]
We would create the temp dir outside the mounted directory. This should also work outside the container or did i miss something?

**Comment by salsolatragus** [comment]
Yes, only we need a way to determine that temp directory such that its location conforms to the environment standard, whatever that may be ;)
