### ISSUE TITLE
Improve formatting of runtimes on review site

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#62]
Currently, the detector runtimes are always displayed in seconds, sometimes as "42.5s", sometimes as "42.s", and sometimes as "4200s" (the latter two indicate that there is are inconsistencies with x.0 and higher numbers...). I would like a consistent formatting and, if possible, also automatically switch to minutes/hours if the runtime exceeds one minute/hour. (This is only for displaying on the website, not for data export, of course).

**Comment by salsolatragus** [comment]
Today I saw that "11022.xx" seconds is formatted to "1102s", thats not only ugly, but plain wrong.

**Comment by joschli** [comment]
The Issue number in my PR was wrong, This was closed by mistake and is not fixed yet
