### ISSUE TITLE
Updating results for detector not supported

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#63]
We do not support updating the results of a detector. Currently, when one does it anyways, the behaviour is strange, because updates go partially through. We should instead give an explicit error message saying that updating is not supported.

**Comment by joschli** [comment]
I realised that with the Refactoring we support partly updating runs. The runs stats for a detector are updated when you push them again, the only thing not updated are its Findings, which are just newly created (basically duplicating them when pushing a detector twice).
Do we want to just extend this by deleting all already existing findings & snippets when pushing a detector again and replacing them with the new ones or do you want me to remove the updating of run stats and send an error when trying to update a detector?

**Comment by salsolatragus** [comment]
We cannot just replace findings, as they might not match existing reviews afterwards. Therefore, the first step is to forbid updates completely, with a meaningful error message.

**Comment by salsolatragus** [comment]
What's the state of this?

**Comment by joschli** [comment]
We still need a timestamp on the client side to identify multiple requests that belong to one run.

**Comment by salsolatragus** [comment]
I now add a 'timestamp' entry to all chunks on upload, which has the same value for all chunks. I think the best place to store this id is the run table, since we cannot upload anything smaller than a run anyways... what do you think?
