### ISSUE TITLE
I can no longer delete snippets in E2

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#64]
The buttons for deleting (and I think even for adding) snippets in E2 disappeared.

**Comment by joschli** [comment]
can you provide a finding with 0 or 2 snippets where it does not work? On my local instance everything is working as intended.

**Comment by salsolatragus** [comment]
I have two snippets, but no delete buttons here: http://mubench2.svamann.de/site/index.php/private/ex3/MuDetectXPOn/closure/319/closure.dmmc-13

I currently can't find an example without snippets and without the form. May have been my imagination...

**Comment by salsolatragus** [comment]
Also, this is not critical. I heard you should be learning ;P

**Comment by joschli** [comment]
This is a finding in experiment 3 where no delete function exists and i have another 30min of a train ride to fill ;)

**Comment by salsolatragus** [comment]
Fair enough. I forgot that this is not E2. Sorry for the false alarm and thanks for looking into it!
