### ISSUE TITLE
Handle invalid file location for detector misuse

### ISSUE THREAD

**Issue by govindsinghnegi** [stg-tud/MUBench#74]
This exception has been observed only with Closure project and the other projects (Itext, Lucene etc.) are working fine. For some reason, the existing Findbugs code to return the Class source path using  "BugInstance.getPrimarySourceLineAnnotation().getSourcePath();" returns an incorrect path. 
A sample output is: "com/google/javascript/jscomp/**_\<Unknown\>_**"
whereas the correct path should have been: "com/google/javascript/jscomp/**_Class-name.java_**"
As you can see that the "class-name.java" part is missing. This leads to a "FileNotFound" exception being thrown while publishing the result to the review site. Logs and yml files are attached.

[logs_and_yml.zip](https://github.com/stg-tud/MUBench/files/1212027/logs_and_yml.zip)

**Comment by salsolatragus** [comment]
In general, a detector returning invalid file paths is a problem that needs fixing on the detector side. However, we should add some more graceful handling of this situation, i.e., not crash and emit a helpful error message.
