### ISSUE TITLE
Support markdown in review comments

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#82]
I would like to use markdown also in review comments. Maybe even with a respective editor, like the one I'm currently typing into ;)

**Comment by joschli** [comment]
what do you think of using [this simple editor](https://github.com/sparksuite/simplemde-markdown-editor) for the comment section when you can edit it (reviewing for yourself/resolution) and rendering the comment with the markdown parser whenever you cannot edit it?

**Comment by salsolatragus** [comment]
Looks good to me.
